### ISSUE TITLE
How to use postcss-js with Webpack? SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by mahnunchik** [postcss/postcss-js#26]
I've faced with the following error:

```bash
ERROR in ./src/test.style.js
Module build failed: /test-webpack/src/test.style.js:3
export default {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.exec (/test-webpack/node_modules/webpack/lib/NormalModule.js:127:12)
    at Promise.resolve.then.then (/test-webpack/node_modules/postcss-loader/lib/index.js:109:18)
    at <anonymous>
```

My `webpack.config.js`:

```js

const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.style.js$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 2 } },
          { loader: 'postcss-loader', options: { parser: 'postcss-js' } },
          'babel-loader'
        ]
      },
    ],
  },
};
```

`index.js`:

```js
import React from 'react';
import ReactDOM from 'react-dom';

import style from './test.style.js';

class Hello extends React.Component {
  render() {
    return <div style={style.main}>Hello World!</div>;
  }
}

ReactDOM.render(
  <Hello />,
  document.getElementById('root')
);
```

`test.style.js`:

```js
export default {
  'main': {
    color: 'black',
    height: 25,
    display: 'flex',
  }
}
```

#### Versions

```bash
$ node -v
v8.1.2
$ npm -v
5.0.3
```

```json
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.0",
    "babel-preset-env": "^1.5.2",
    "babel-preset-react-app": "^3.0.0",
    "css-loader": "^0.28.4",
    "postcss-js": "^1.0.0",
    "postcss-loader": "^2.0.6",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "style-loader": "^0.18.2",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.5.0",
```

**Comment by ai** [comment]
You should ask `postcss-loader`, because issue goes from webpack config
